### ISSUE TITLE
Documentation/README

### ISSUE THREAD

**Issue by mattbell87** [2pisoftware/cmfive-boilerplate#126]
Readme.md needs to be changed to include or link to more info:

- Instructions for developing (rework the current info?)
   - Docker compose file is for development, how to get started
   - Explain how volumes are mapped with the compose file
   - Execute cmfive.php with the container `docker compose exec -it webapp php cmfive.php`
   - Running playwright and phpunit
   - Remove or update mkcert info? (any objection to just letting people ignore warnings?)
- Docker image details
  - Environment variables
      - DB_HOST
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - ENVIRONMENT
  - Build args
      - CORE_BRANCH
      - PHP_VERSION
  - Volumes to mount in /var/www/html for persistence
      - ./storage
      - ./uploads
      - ./backups
   - Ports
      - 80
      - 443
   - SSL/TLS Certificate mounting 
      - Mention the self signed certificate that's built in to the image and how to override it (another volume mount)
- Instructions for deploying cmfive
  - Docker
  - CDK?
  - Manual Nginx/Apache/PHP/MySQL etc

**Comment by chris-bateman** [comment]
A good read here for what to potentially include.
https://opensource.guide/

Think about another person using this project from scratch.

**Comment by chris-bateman** [comment]
https://github.com/2pisoftware/cmfive-core/issues/275
