### ISSUE TITLE
Removal of glob-fs

### ISSUE THREAD

**Issue by chris-bateman** [2pisoftware/cmfive-boilerplate#98]
Remove glob-fs due to security issues.
Detected by -
https://github.com/2pisoftware/cmfive-boilerplate/security/dependabot/4
https://github.com/2pisoftware/cmfive-boilerplate/security/dependabot/5
https://github.com/2pisoftware/cmfive-boilerplate/security/dependabot/6
https://github.com/2pisoftware/cmfive-boilerplate/security/dependabot/7
https://github.com/2pisoftware/cmfive-boilerplate/security/dependabot/8

https://github.com/2pisoftware/cmfive-boilerplate/blob/06a583f8cf55b5d64bb64838b4faeca6cbeebf86/test/playwright/package.json#L18

![image](https://github.com/2pisoftware/cmfive-boilerplate/assets/12206103/60e58577-5406-47e7-b761-0394cd040520)

A search of the codebase reveals that glob-fs is not used.  Glob and fs are used independently.  I suspect glob-fs was added during early development.

Please advise if glob-fs can be removed and playwright rebuilt without it.

**Comment by chris-bateman** [comment]
@2pisoftware/developers Please review

**Comment by Dane-2pi** [comment]
@dragonflyfree 
You'll have the best idea

**Comment by dragonflyfree** [comment]
good to remove, tests run fine without it afaict

**Comment by chris-bateman** [comment]
@dragonflyfree are you good to open a PR?

**Comment by dragonflyfree** [comment]
on it !
